sudo: true
dist: trusty
cache:
  directories:
    - backend/node_modules
    - labtool2.0/node_modules

notifications:
  email: false
language: node_js
node_js:
- '8'
before_install:
- cd labtool2.0 && npm config set spin false && npm install -g npm && cd ../backend && npm config set spin false && cd ..
install:
- cd labtool2.0 && npm install && cd ../backend && npm install && cd ..
before_script:
- cd backend; npm run create_test_db; cd ..
after_script:
- cd ../backend; npm run drop_test_db
jobs:
  include:
  - stage: tests
    script: cd backend && npm run test
    env: BACKEND=true
  - stage: tests
    script: cd labtool2.0 && CI=true npm test
    env: FRONTEND=true
  - stage: integration tests
    script: TRAVIS_ALLOW_FAILURE=true echo "Nothing yet"
