version: '3'
services:
  web:
    image: labtool/labtool:dev
    ports:
     - "3000:3000"
    depends_on:
     - backend
  backend:
    environment:
      TOKEN: "changeme"
      ENV: "test"
    image: labtool/labtool-backend:dev
    ports:
      - "3001:3001"
    depends_on:
      - db
  db:
    environment:
      PGDATA: /data/pg10.1_labtool_2018k
    volumes:
      - /data/pg10.1_labtool_2018k:/data/pg10.1_labtool_2018k
    image: postgres:10.1
    restart: unless-stopped
